### PR TITLE
Add types generation

### PR DESCRIPTION
**Pull request by strdr4605**

### CODE REVIEW

**Comment by micnic** [comment]
Oh, nice upgrade, will have to add some more improvements to the package build functionality

**Comment by strdr4605** [comment]
Too bad it wasn't considered a Hacktoberfest PR 😅

**Comment by strdr4605** [comment]
Screenshot 2021-10-06 at 10 45 06

@micnic can you please add `hacktoberfest-accepted` label to this PR?

**Comment by micnic** [comment]
Added

**Pull request merged**
